### ISSUE TITLE
edx-django-utils readthedocs is failing to build

### ISSUE THREAD

**Issue by robrap** [openedx/edx-django-utils#301]
### Firm Name

2U

### Urgency

Medium (< 2 weeks)

### Problem/Request

The readthedocs build https://readthedocs.org/projects/edx-django-utils/ is failing for some reason.

### Reasoning

It's broken.

**Comment by sarina** [comment]
@feanil is this something that could go on the docs backlog?

**Comment by feanil** [comment]
Yep, I'll add it there.  @robrap The failing build output is here it looks like an issue with the requirements: https://readthedocs.org/projects/edx-django-utils/builds/20309157/

I can dig into it next week if you don't get to it before then.

**Comment by robrap** [comment]
@feanil: Others determined that it might be a Python 3.7 vs Python 3.8 issue. I wonder if you could switch this repo to use a new config file like https://github.com/openedx/edx-platform/blob/master/.readthedocs.yaml so we could self-manage fixing in the future.

I’m not sure if the config file is in the cookie-cutter, but the more of this in GitHub the less it is restricted to Axim fixing.

Thanks.

**Comment by robrap** [comment]
Becca is adding the appropriate config file in https://github.com/openedx/edx-django-utils/pull/303. If it automatically gets picked up by readthedocs, we’ll close this ticket. If not, a simple admin setting change in readthedocs to point to the new config file should be enough.

**Comment by rgraber** [comment]
If we want to set up readthedocs to fail on warning the way we do for open-edx-proposals, we'll need to fix a bunch of warnings that autodoc is throwing when it tries to create documentation for the code proper. I don't think it's worth trying to fix all of those as part of the initial issue but can file another and leave it as a TODO in the readthedocs.yaml file.

**Comment by rgraber** [comment]
FYI the build is now passing on Readthedocs.

**Comment by robrap** [comment]
[inform] I added a note on #304 about the corresponding Makefile change that is needed.
