### ISSUE TITLE
[APM] Add Datadog support to edx-django-utils

### ISSUE THREAD

**Issue by timmc-edx** [openedx/edx-django-utils#389]
A/C:

- [x] Telemetry functions that report to New Relic can also report to Datadog
- [x] Does not introduce any required runtime dependency on Datadog

To support Datadog in Open edX, we'll need to expand the telemetry reporting in edx-django-utils to report to both New Relic and to Datadog. We may choose to implement this via OpenTelemetry support (as there is a way to export that to DD) or by direct reference to DD.

This is part of https://github.com/edx/edx-arch-experiments/issues/571

Implementation notes:

- New setting: List of implementations (NR, DD, OTel) for receiving telemetry.
  - Defaults to just NR (may change in the future)
- Telemetry utility functions fan out to all implementations in the list
- PR: https://github.com/openedx/edx-django-utils/pull/397

Code to consider for update:

- Anything that imports `newrelic`
- Anything imported and re-exposed in `edx_django_utils/monitoring/__init__.py`

**Comment by robrap** [comment]
[proposal] Refactor edx-django-utils monitoring API to allow configurable implementation:
* Maintain backward compatibility. Make New Relic the default.
* Split implementation (OTEL vs New Relic vs Logging) from the interface.
* Consider making the implementation configurable via a list, so we could send to OTEL and New Relic in parallel.

What do you think of this alternative plan?

**Comment by robrap** [comment]
@timmc-edx: Reminder to clean-up or close this ticket.

**Comment by timmc-edx** [comment]
Updated for current plans (DD support as plugin)

**Comment by timmc-edx** [comment]
This part is done. Rollout will be covered by https://github.com/edx/edx-arch-experiments/issues/571
