### ISSUE TITLE
Add Datadog support for span-related monitoring functions

### ISSUE THREAD

**Issue by timmc-edx** [openedx/edx-django-utils#419]
[Consider breaking out each method as its own ticket when this is to be picked up.] 

Acceptance criteria:

- [ ] Complete all of the following for each method:
  - [x] `function_trace`: https://github.com/openedx/edx-django-utils/pull/435
    - [x] Move implementation into `NewRelicBackend`.
    - [x] Implement in `DatadogBackend`.
    - [x] Update function to call all of the telemetry backends.
    - [x] `edx_django_utils/monitoring/README.rst` updated with latest compatibility info.
    - [x] Inform owners of calling code, especially for backward-incompatible changes in Datadog.
  - [x] `set_monitoring_transaction_name`
    - [x] Move implementation into `NewRelicBackend`.
    - [x] Implement in `DatadogBackend`.
    - [x] Update function to call all of the telemetry backends.
    - [x] `edx_django_utils/monitoring/README.rst` updated with latest compatibility info.
    - [x] Inform owners of calling code, especially for backward-incompatible changes in Datadog (see notes).
  - [x] `ignore_transaction`
    - [x] Move implementation into `NewRelicBackend`.
    - [x] Implement in `DatadogBackend`.
    - [x] Update function to call all of the telemetry backends.
    - [x] `edx_django_utils/monitoring/README.rst` updated with latest compatibility info.
    - [x] Inform owners of calling code, especially for backward-incompatible changes in Datadog.
  - [ ] Handle `get_current_transaction` appropriately (see notes).
  - [ ] Handle `background_task` appropriately (see notes).

Implementation notes:

- Optionally, choose new names that are less specific to NR, and deprecate the old names (leaving stubs in their place that emit a warning and call the new function).

Other notes:

- Some repos currently call these directly on `newrelic.agent` rather than using edx-django-utils's indirection. https://github.com/edx/edx-arch-experiments/issues/621 covers resolving this.
- It appears that `get_current_transaction` is currently only used internally, despite being exposed, so it can probably be skipped for now.
- Relatedly, `background_task` appears to be completely unused. (Should this be retired?)
- 2U did not end up using OpenTelemetry, so we can't commit to adding support to OpenTelemetryBackend at the moment. These new methods can be implemented as no-ops in that backend.
- The method `set_monitoring_transaction_name` is [used for XBlocks here](https://github.com/openedx/edx-platform/blob/0c2a919c3a1b13aabbbccb4172e5b35b6c69da04/lms/djangoapps/courseware/block_render.py#L941), and the resource name will probably change, which may affect monitoring or other XBlock related observability.

**Comment by robrap** [comment]
Note that `function_trace` has since been implemented.

**Comment by robrap** [comment]
Additional Notes:
- What remains is NR transaction-related calls: `set_monitoring_transaction_name` and `ignore_transaction` (found in [transactions.py](https://github.com/openedx/edx-django-utils/blob/master/edx_django_utils/monitoring/internal/transactions.py))
- The closest thing to a NR transaction in Datadog (and OpenTelemtry) is the Span.
- In Datadog, we probably want `set_monitoring_transaction_name` to update the resource name only (not operation name). I think the more general `name` goes to both the resource and operation name.

**Comment by robrap** [comment]
I updated AC and moved this to P3, since these methods are in use. It would be great to confirm and retire what is not in use(see notes).
